config/routes.rb
Personalis::Application.routes.draw do
  


  resources :categories


  #ROUTES CAMPINGS

  resources :campaigns do
      get 'user'
      post 'update_user'
  end

  
  #ROUTES KIES
  resources :keys

  #ROUTES PROFILE
  resources :profiles

  # ROUTES FOR DEVISE
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},controllers: {omniauth_callbacks: "omniauth_callbacks"}
  

  authenticated :user do
    root :to => 'users#profile'
  end
  
  root :to => "home#index"
  


  resources :users do
    collection do
        get 'metrics'
    end
  
  end
end

app/models/campaign.rb
class Campaign
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :influenciador , type: String

  has_many :categories
  belongs_to :user
end

app/controllers/campaigns_controller.rb
require 'topsy'

class CampaignsController < ApplicationController
  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign = Campaign.find(params[:id])
    @hastag = Topsy.phrase_tweets('hola')
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.json
  def new
    @campaign = Campaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(params[:campaign])

    respond_to do |format|
      if current_user.campaigns << @campaign
        format.html { redirect_to campaign_user_path(@campaign), notice: 'Campaign was successfully created.' }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.json
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end

  def user
      @camp = Campaign.find(params[:campaign_id])
      @user = User.all
  end

  def update_user
    @campaign = Campaign.find(params[:campaign_id])
    @user = User.find(params[:user])
    @campaign.update_attributes(influenciador: @user.id )
    respond_to do |format|
      format.html { redirect_to @campaign }
      format.json { head :no_content }
    end
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<form class="form-search">
  <legend>Buscar perfil</legend>
    <input type="text" class="input-medium search-query">
      <button type="submit" class="btn">Search</button>
    </form>
<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_de_la_campana %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label>categoria </label><br />
    
<%= collection_select(:category, :category_id, Category.all, :id, :name, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :tweet %><br />
    <%= f.text_area :description, :rows => "5" %>
  </div>
  <div class="actions">
    <%= f.submit 'Crear campaña', :class => "btn btn-large btn-custom-form" %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<div id="contForm">
  <div class="container">
    <h1>Campañas</h1>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Nombre de la campaña</th>
          <th>Categoria</th>
          <th>Tweet</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>

      <% @campaigns.each do |campaign| %>
        <tr>
          <td><%= campaign.name %></td>
          <td><%= campaign.description %></td>
          <td>Cat</td>
          <td><%= link_to 'Show', campaign %></td>
          <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
          <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
    </table>

    <br />

    <%= link_to 'Crear campaña', new_campaign_path, :class => "btn btn-large btn-custom-form" %>
  </div>
</div>

app/views/campaigns/new.html.erb
<div id="contForm">
  <div class="container">
    <h1>Crea una nueva campaña</h1>

    <%= render 'form' %>

    <%= link_to 'Back', campaigns_path %>
  </div>
</div>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @campaign.name %>
</p>

<p>
  <b>Description:</b>
  <%= @campaign.description %>
</p>


<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>

<%= debug @hastag %>

app/views/campaigns/user.html.erb
<div id="contForm">
<div class="container">

<%= form_tag (campaign_update_user_path(@camp)) do %>
 <table class="table">
  <tr>
    <th>chech</th>
    <th></th>
    <th>Nombre</th>
    <th>Precio</th>
    <th>Categoria</th>
  </tr>
  
  <% @user.each do |user| %>
  <tr>
    <td><%= radio_button_tag(:user, user.id) %></td>
    <td><%= image_tag user.image%></td>
    <td><%= user.name %></td>
    <td></td>
    
  </tr>
  <% end -%>


  <% end %>

</table>
 <%= submit_tag  %>
</div>
</div>